---
title: 자바스크립트 이벤트 루프
date: '2022-02-23'
tags: ['javascript', 'event-loop']
draft: true
summary: 자바스크립트의 이벤트 루프에 대해 알아보고, 동작 원리를 이해하자.
---

## 참고 코드를

아래 코드에서 `catch`는 `Error`를 잡아 낼 수 잇는가?

- https://stackoverflow.com/questions/48969591/why-promise-can-not-catch-the-error-throw-by-settimeout
- https://www.youtube.com/watch?v=8aGhZQkoFbQ
- [rejectionhandled](https://developer.mozilla.org/en-US/docs/Web/API/Window/rejectionhandled_event)
- [PromiseRejectionEvent](https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent)

```js
// (1)
new Promise(function (resolve, reject) {
  setTimeout(() => {
    throw new Error('에러 발생!')
  }, 1000)
})
  .then(() => console.log('then'))
  .catch(() => console.error('error'))

// (2)
new Promise(function (resolve, reject) {
  setTimeout(() => {
    reject(new Error('error'))
  }, 1000)
})
  .then(() => console.log('then!!'))
  .catch(() => console.error('error!!'))
```

---

```js
function fetchImage(url, callback) {
  var xmlHttp = new XMLHttpRequest()

  xmlHttp.onreadystatechange = function () {
    if (xmlHttp.readyState === xmlHttp.DONE) {
      if (this.status === 200) {
        callback(null, this.response) // (1)
      } else {
        callback(new Error('실패')) // (1)
      }
    }
  }
  xmlHttp.open('GET', url)
  xmlHttp.send()
}
undefined
function handlePhoto(error, photo) {
  if (error) console.error('Download error!', error)
  else console.log('Download finished', photo)
}

undefined
fetchImage('https://picsum.photos/500', handlePhoto)
console.log('started')
```

## 참고 레퍼런스

- [loupe](http://latentflip.com/loupe)
- [queueMicrotask](https://www.freecodecamp.org/news/queuemicrotask/)
- https://kay0426.tistory.com/25
- https://dev.to/lydiahallie/javascript-visualized-event-loop-3dif
